# Copyright (C) Viktor Szakats. See LICENSE.md
# SPDX-License-Identifier: MIT

# https://docs.github.com/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: '[ci skip]'
    cooldown:
      default-days: 30
      semver-major-days: 30
      semver-minor-days: 30
      semver-patch-days: 30
    groups:
      actions-deps:
        patterns:
          - '*'

  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'monthly'
    cooldown:
      default-days: 7
      semver-major-days: 15
      semver-minor-days: 7
      semver-patch-days: 3
    commit-message:
      prefix: '[ci skip]'
