# Copyright (C) Viktor Szakats. See LICENSE.md
# SPDX-License-Identifier: MIT

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: "[ci skip]"

  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: "[ci skip]"
