# Copyright (C) Viktor Szakats. See LICENSE.md
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
version: '1.0.{build}'
branches:
  only:
    - 'main'
    - 'main-libressl'
    - 'main-quictls'
    - 'main-boringssl'
    - 'main-awslc'
    - 'main-mini'
    - 'dev'
    - 'dev-libressl'
    - 'dev-quictls'
    - 'dev-boringssl'
    - 'dev-awslc'
    - 'dev-mini'
    - 'test'
    - 'test-libressl'
    - 'test-quictls'
    - 'test-boringssl'
    - 'test-awslc'
    - 'test-mini'
# https://www.appveyor.com/docs/build-environment/#build-worker-images
# https://www.appveyor.com/docs/linux-images-software/
image: 'Ubuntu2204'
services:
  - 'docker'
clone_depth: 8
build:
  verbosity: 'detailed'
environment:
  CW_LLVM_MINGW_DL: '1'
  CW_LLVM_MINGW_ONLY: '0'
  CW_MAP: '0'
  CW_JOBS: '2'
  SIGN_CODE_GPG_PASS:
    secure: 'GalldmjiSv7Zkxb+W9T2ccx8M58tEJx6vXIs75szSPAVGH3Tl6s/IjIfdYhcjKQf'
  SIGN_CODE_KEY_PASS:
    secure: 'dGiua20PNhgaxUGN2xEksAsyeobYHBu6Sh3OJFMGT7qvJRE8h+CoZ0MzRGWrrLxk'
  SIGN_PKG_KEY_ID: 'BDCF067D3908B2727A4A948767C1003740BF8DC2'
  SIGN_PKG_GPG_PASS:
    secure: '691Ykt37/bFaTvxSafrjxGf9Y0konF/jLO3DbglIjMeaHW6FwIqsi8r6KASIjdGU'
  SIGN_PKG_KEY_PASS:
    secure: 'hPd2pmh39DzHjaINLeLKHl3VGVuAuRlLt05nhU7fph55KBeTBjtkHNaKUxBu+3Ev'
  DEPLOY_GPG_PASS:
    secure: 'zb5hAQukLzixNEtXf2rM4gozjsa1jdxzc+Dq+XzEvu19wn/YRplfvM2euY4N5t3g'
  DEPLOY_KEY_PASS:
    secure: 'CS5o1b7BhBEmoEq+RFaTmtWpAd3HqHLqnpJvkAjF+DmnlJVPLo34MeusmnJ56wAX'
  DO_NOT_TRACK: '1'
  DOCKER_CONTENT_TRUST: ''
build_script:
  - sh: |
      export CW_CONFIG="${APPVEYOR_REPO_BRANCH}-win"
      . ./_versions.sh
      docker trust inspect --pretty "${DOCKER_IMAGE}"
      time docker pull "${DOCKER_IMAGE}"
      docker images --digests
      time docker run --volume="$(pwd):$(pwd)" --workdir="$(pwd)" \
        --env-file=<(env | grep -a -E \
          '^(CW_|SIGN_|DEPLOY_|APPVEYOR_|CI_|DO_NOT_TRACK)') \
        "${DOCKER_IMAGE}" \
        sh -c ./_ci-linux-debian.sh

artifacts:
  - path: '*-*-mingw*.*'
    name: 'package'
  - path: 'all-mingw*.*'
    name: 'all'

# init:
#   - sh: curl --disable --user-agent '' --fail --silent --location --proto-redir =https 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
